/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as MyProjectsRouteImport } from './routes/my-projects'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UploadProgressRouteImport } from './routes/upload-progress'
import { Route as UploadProjectRouteImport } from './routes/upload-project'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProjectsRoute = MyProjectsRouteImport.update({
  id: '/my-projects',
  path: '/my-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadProgressRoute = UploadProgressRouteImport.update({
  id: '/upload-progress',
  path: '/upload-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadProjectRoute = UploadProjectRouteImport.update({
  id: '/upload-project',
  path: '/upload-project',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/applications': typeof ApplicationsRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/my-projects': typeof MyProjectsRoute
  '/recommendations': typeof RecommendationsRoute
  '/roadmap': typeof RoadmapRoute
  '/roi': typeof RoiRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/upload-progress': typeof UploadProgressRoute
  '/upload-project': typeof UploadProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/applications': typeof ApplicationsRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/my-projects': typeof MyProjectsRoute
  '/recommendations': typeof RecommendationsRoute
  '/roadmap': typeof RoadmapRoute
  '/roi': typeof RoiRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/upload-progress': typeof UploadProgressRoute
  '/upload-project': typeof UploadProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/applications': typeof ApplicationsRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/my-projects': typeof MyProjectsRoute
  '/recommendations': typeof RecommendationsRoute
  '/roadmap': typeof RoadmapRoute
  '/roi': typeof RoiRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/upload-progress': typeof UploadProgressRoute
  '/upload-project': typeof UploadProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/applications'
    | '/architecture'
    | '/dashboard'
    | '/duplicates'
    | '/my-projects'
    | '/recommendations'
    | '/roadmap'
    | '/roi'
    | '/services'
    | '/settings'
    | '/upload-progress'
    | '/upload-project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/applications'
    | '/architecture'
    | '/dashboard'
    | '/duplicates'
    | '/my-projects'
    | '/recommendations'
    | '/roadmap'
    | '/roi'
    | '/services'
    | '/settings'
    | '/upload-progress'
    | '/upload-project'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/applications'
    | '/architecture'
    | '/dashboard'
    | '/duplicates'
    | '/my-projects'
    | '/recommendations'
    | '/roadmap'
    | '/roi'
    | '/services'
    | '/settings'
    | '/upload-progress'
    | '/upload-project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DashboardRoute: typeof DashboardRoute
  DuplicatesRoute: typeof DuplicatesRoute
  MyProjectsRoute: typeof MyProjectsRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RoadmapRoute: typeof RoadmapRoute
  RoiRoute: typeof RoiRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  UploadProgressRoute: typeof UploadProgressRoute
  UploadProjectRoute: typeof UploadProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-projects': {
      id: '/my-projects'
      path: '/my-projects'
      fullPath: '/my-projects'
      preLoaderRoute: typeof MyProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-progress': {
      id: '/upload-progress'
      path: '/upload-progress'
      fullPath: '/upload-progress'
      preLoaderRoute: typeof UploadProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-project': {
      id: '/upload-project'
      path: '/upload-project'
      fullPath: '/upload-project'
      preLoaderRoute: typeof UploadProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  ApplicationsRoute: ApplicationsRoute,
  ArchitectureRoute: ArchitectureRoute,
  DashboardRoute: DashboardRoute,
  DuplicatesRoute: DuplicatesRoute,
  MyProjectsRoute: MyProjectsRoute,
  RecommendationsRoute: RecommendationsRoute,
  RoadmapRoute: RoadmapRoute,
  RoiRoute: RoiRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  UploadProgressRoute: UploadProgressRoute,
  UploadProjectRoute: UploadProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
